Repository Programmers-Coach-Coach/Coach-Coach-client, pull requests merged in 2024-11, with the labels that each got.

#360 Feat: 코치 리스트 변경
  src/assets/images/filter.svg
  src/assets/images/search.svg
  src/assets/images/x-circle.svg
  src/components/coach/BasicInfo.tsx
  src/components/coach/CaochListFilter.tsx
  src/components/coach/Coach.tsx
  src/components/coach/CoachList.tsx
  src/components/coach/CoachListFilter.tsx
  src/components/common/Chip/SportChip.tsx
  src/components/common/InputField/search/Search.tsx
  src/components/common/modal/contents/FilterPicker.tsx
  src/components/common/modal/contents/RadioContent.tsx
  src/components/common/modal/contents/filterPicker/FilterPicker.css.ts
  src/components/common/modal/contents/filterPicker/FilterPicker.tsx
  src/components/common/modal/contents/filterPicker/GenderFilter.tsx
  src/components/common/modal/contents/filterPicker/GenderRadio.tsx
  src/components/common/modal/contents/filterPicker/SortFilterList.tsx
  src/components/common/modal/contents/filterPicker/SportsFilterList.tsx
  src/constants/assets.tsx
  src/constants/filter.ts
  src/hooks/useCoachFilter.ts
  src/hooks/useCoachList.ts
  src/hooks/useQueryString.ts
  src/pages/CoachList.tsx
  src/style/global.ts
  src/style/theme.ts
Labels: enhancement

#362 신체 기록 디자인 변경
  src/api/record.api.ts
  src/assets/images/stamp.png
  src/assets/images/stamp.svg
  src/components/chart/LineChart.tsx
  src/components/common/modal/contents/AddPhysicalContent.tsx
  src/components/modal/PhysicalRecordInner.tsx
  src/components/record/exerciseRecord/ExerciseCalendar.tsx
  src/components/record/exerciseRecord/ExerciseDetail.tsx
  src/components/record/physicalRecord/PhysicalDetailRecord.tsx
  src/components/record/physicalRecord/PhysicalRecord.tsx
  src/components/record/physicalRecord/PhysicalRecordChart.tsx
  src/components/record/physicalRecord/PhysicalRecordInputs.tsx
  src/constants/apiPath.ts
  src/hooks/queries/useRecord.ts
  src/hooks/useQueryString.ts
  src/pages/Record.tsx
  src/pages/RecordDatail.tsx
  src/utils/format.ts
Labels: enhancement

#367 Feat: 홈 API 분리 반영
  src/App.tsx
  src/api/home.api.ts
  src/api/review.api.ts
  src/components/Profile/CoachProfile.tsx
  src/components/coach/AddReview.tsx
  src/components/coach/CoachDetails.tsx
  src/components/coach/CoachList.tsx
  src/components/coach/PopularCoach.tsx
  src/components/coach/Review.tsx
  src/components/coach/ReviewCardList.tsx
  src/components/coaches/PopularCoaches.tsx
  src/components/common/Card/ReviewCard.tsx/RatingStars.tsx
  src/components/common/InputField/CheckBox/Heart.tsx
  src/components/common/modal/contents/RadioContent.tsx
  src/components/sports/SportsList.tsx
  src/constants/apiPath.ts
  src/hooks/queries/useLikes.ts
  src/hooks/useHome.ts
  src/pages/Home.tsx
  src/utils/masking.ts
Labels: enhancement

#369 Feat: 알림 UI 변경
  src/App.tsx
  src/assets/images/notification.svg
  src/assets/images/x.svg
  src/components/card/NotificationCard.tsx
  src/components/layout/Layout.tsx
  src/constants/assets.tsx
  src/pages/CoachList.tsx
  src/pages/Notification.tsx
Labels: Design

#371 Feat: 모달 관련 기능 추가
  src/components/coach/CoachListFilter.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/contents/OneButtonContent.tsx
  src/components/common/modal/contents/filterPicker/FilterPicker.css.ts
  src/components/common/modal/contents/filterPicker/FilterPicker.tsx
  src/components/common/modal/contents/filterPicker/GenderFilter.tsx
Labels: enhancement, Design

#380 Feat: 알림 조회 및 기록 UI 연결
  src/components/Profile/CoachProfile.tsx
  src/components/card/NotificationCard.tsx
  src/components/common/Footer/Footer.tsx
  src/components/record/exerciseRecord/ExerciseDetail.tsx
  src/components/routine/RecordRoutine.tsx
  src/components/routine/RecordRoutineList.tsx
  src/models/notification.model.ts
  src/models/record.model.ts
  src/pages/Coach.tsx
  src/pages/Notification.tsx
  src/pages/RecordDatail.tsx
Labels: enhancement

#382 Fix: 오타 수정
  src/components/coach/Introduction.tsx
  src/constants/apiPath.ts
  src/constants/filter.ts
Labels: bug

#388 Refactor: 코치프로필 에러 수정
  src/components/common/InputField/Text/CommonInput.tsx
  src/components/mypage/AddressSearchField.tsx
  src/components/mypage/CoachProfileSection.tsx
  src/hooks/queries/useFetchCoachProfile.ts
Labels: Refactor

#392 Refactor: UI수정
  src/pages/Mypage.tsx
Labels: Refactor

#394 Refactor : 코치 UI 수정
  src/components/coach/CoachDetails.tsx
  src/components/coach/Introduction.tsx
  src/pages/CoachList.tsx
Labels: Refactor

#401 Change: coach/ 폴더 분리
  src/App.tsx
  src/components/coach/detail/ActiveCenterMap.tsx
  src/components/coach/detail/CoachDetails.tsx
  src/components/coach/detail/Introduction.tsx
  src/components/coach/detail/MatchButtons.tsx
  src/components/coach/detail/Summary.tsx
  src/components/coach/list/CoachCard.tsx
  src/components/coach/list/CoachList.tsx
  src/components/coach/list/CoachListFilter.tsx
  src/components/coach/list/PopularCoach.tsx
  src/components/coach/list/PopularCoaches.tsx
  src/components/coach/review/AddReview.tsx
  src/components/coach/review/AddReviewInner.tsx
  src/components/coach/review/Review.tsx
  src/components/coach/review/ReviewCard.tsx
  src/components/coach/review/ReviewCardList.tsx
  src/components/modal/ReviewControl.tsx
  src/components/modal/ReviewInner.tsx
  src/pages/Coach.tsx
  src/pages/CoachList.tsx
  src/pages/Home.tsx
Labels: enhancement

#403 Refactor: 알림 및 코치 관련 페이지 UI/UX 변경
  src/api/coach.api.ts
  src/assets/images/alarm.svg
  src/components/badge/NotificationBadge.tsx
  src/components/card/NotificationCard.tsx
  src/components/coach/detail/ActiveCenterMap.tsx
  src/components/coach/filter/GenderFilter.tsx
  src/components/coach/filter/SortFilterList.tsx
  src/components/coach/filter/SportsFilterList.tsx
  src/components/coach/list/CoachList.tsx
  src/components/coach/list/CoachListFilter.tsx
  src/components/coach/review/Review.tsx
  src/components/common/Header/LogoHeader.tsx
  src/components/common/modal/contents/filter/CoachListFilter.tsx
  src/components/common/modal/contents/filter/GenderRadio.tsx
  src/components/common/modal/contents/filter/ReviewFilter.tsx
  src/components/record/exerciseRecord/ExerciseCalendar.tsx
  src/constants/assets.tsx
  src/hooks/useCoachList.ts
  src/hooks/useQueryString.ts
  src/pages/Notification.tsx
  src/style/Filter.css.ts
Labels: enhancement, Design

#405 Style: 자기소개 텍스트 줄바꿈 처리
  src/components/coach/detail/Introduction.tsx
Labels: enhancement, Design

#407 Modify: 채팅 버튼 문구 등 여러가지 변경
  src/components/coach/detail/MatchButtons.tsx
  src/components/record/exerciseRecord/ExerciseCalendar.tsx
Labels: bug, enhancement, Design
