Repository Programmers-Coach-Coach/Coach-Coach-client, pull requests merged in 2024-10, with the labels that each got.

#327 Refactor/first page
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/Logo.png
  src/assets/images/alarm-image.svg
  src/assets/images/check-icon.svg
  src/assets/images/checked-icon.svg
  src/assets/images/email-icon.svg
  src/assets/images/google-icon.svg
  src/assets/images/kakao-image.svg
  src/assets/images/kakaoLogin.png
  src/assets/images/lock-icon.svg
  src/assets/images/logo.svg
  src/assets/images/record-image.svg
  src/assets/images/routine-image.svg
  src/assets/images/signup-success-icon.svg
  src/assets/images/user-icon.svg
  src/components/common/Button/CustomButton.tsx
  src/components/common/InputField/Text/AuthInput.tsx
  src/components/common/InputField/Text/CommonInput.tsx
  src/components/layout/Layout.tsx
  src/components/login/LoginForm.tsx
  src/components/signup/SignupForm.tsx
  src/hooks/useAuth.ts
  src/pages/First.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
  src/pages/TotalLogin.tsx
  src/style/theme.ts
  src/utils/getTitle.ts
  src/utils/isAuthPage.ts
Labels: enhancement, Refactor, Design

#333 Refactor/mypage refactor
  src/App.tsx
  src/assets/images/arrow-icon.svg
  src/assets/images/edit-icon.svg
  src/components/common/Button/CustomButton.tsx
  src/components/common/Header/LogoHeader.tsx
  src/components/common/HorizontalLine/HorizontalLine.tsx
  src/components/common/InputField/Select/GenderSelectBox.tsx
  src/components/common/InputField/Select/SportSelectBox.tsx
  src/components/common/InputField/Text/CommonInput.tsx
  src/components/common/modal/Modal.tsx
  src/components/mypage/AddressSearchField.tsx
  src/components/mypage/CoachProfileSection.tsx
  src/components/mypage/ProfileSection.tsx
  src/components/signup/SignupForm.tsx
  src/components/tab/DefaultTab.tsx
  src/pages/CheckPassword.tsx
  src/pages/Mypage.tsx
  src/pages/Profile.tsx
  src/style/theme.ts
  src/utils/getTitle.ts
Labels: enhancement, Refactor, Design

#336 Feat : 카카오, 구글 소셜로그인 구현
  src/components/login/LoginForm.tsx
  src/pages/TotalLogin.tsx
Labels: enhancement

#340 Refactor: 코치프로필 문의가능시간 수정
  package-lock.json
  package.json
  src/components/mypage/CoachProfileSection.tsx
  src/components/mypage/ProfileSection.tsx
Labels: Refactor

#344 Refactor: 관심, 코칭 종목 개수 제한
  src/components/common/InputField/Select/SportSelectBox.tsx
Labels: Refactor

#346 Chore: vite-plugin-svgr 설치하여 동적으로 아이콘 색상, 사이즈 변경
  package-lock.json
  package.json
  src/assets/images/empty-heart.svg
  src/assets/images/full-heart.svg
  src/components/Icon/SvgIcon.tsx
  src/components/common/InputField/CheckBox/Heart.tsx
  src/constants/assets.tsx
  src/vite-env.d.ts
  vite.config.ts
Labels: Chore

#348 Feat: 홈 화면 디자인 변경
  src/assets/images/arrow-down.svg
  src/assets/images/full-star.svg
  src/assets/images/star.svg
  src/assets/images/topRanks/top-rank-1.svg
  src/assets/images/topRanks/top-rank-2.svg
  src/assets/images/topRanks/top-rank-3.svg
  src/components/Icon/SvgIcon.tsx
  src/components/coach/Coach.tsx
  src/components/coach/PopularCoach.tsx
  src/components/coach/PopularCoaches.tsx
  src/components/coaches/PopularCoaches.tsx
  src/components/common/InputField/CheckBox/Heart.tsx
  src/components/sport/HomeSport.tsx
  src/components/sports/SportsList.tsx
  src/constants/assets.tsx
  src/pages/Home.tsx
Labels: Design

#351 Refactor: Api 버전 v1 -> v2로 업데이트 되어 v1 경로 변경
  src/api/http.ts
  src/components/common/Footer/Footer.tsx
  src/components/common/Header/LogoHeader.tsx
  src/constants/apiPath.ts
  src/utils/getTitle.ts
Labels: enhancement
