Repository Programmers-Coach-Coach/Coach-Coach-client, pull requests merged in 2024-07, with the labels that each got.

#4 Chore: GitHub action CI 구축
  .babelrc
  .eslintrc.cjs
  .github/workflows/CI.yml
  .github/workflows/eslint.yml
  .nvmrc
  jest.config.cjs
  package-lock.json
  package.json
  src/__tests__/App.test.tsx
Labels: enhancement, Chore

#7 Feat : glabal 스타일링 및 테마 설정
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/__tests__/__snapshots__/theme.test.ts.snap
  src/__tests__/theme.test.ts
  src/style/global.ts
  src/style/theme.ts
Labels: enhancement

#10 Refactor: theme.test.ts 수정
  src/__tests__/theme.test.ts
Labels: enhancement

#12 Refactor: 웹폰트 최적화
  index.html
Labels: enhancement

#15 Fix: 화면너비 조절 및 폰트 포맷 수정
  src/App.tsx
  src/style/global.ts
Labels: enhancement

#21 Feat: CustomButton 공통 컴포넌트 구현
  src/components/common/CustomButton.tsx
Labels: enhancement

#23 Feat/layout
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/Logo.png
  src/assets/images/a.txt
  src/components/common/Footer/Footer.tsx
  src/components/common/Header/DetailHeader.tsx
  src/components/common/Header/LogoHeader.tsx
  src/components/layout/Layout.tsx
  src/pages/Detail.tsx
  src/pages/Error.tsx
  src/pages/Home.tsx
Labels: enhancement

#29 Refactor/ci icon
  .github/workflows/CI.yml
  src/components/common/Footer/Footer.tsx
  src/constants/assets.tsx
  src/data/a.ts
Labels: Refactor

#31 Refactor: theme.ts, CustomButtom.tsx 수정
  src/__tests__/__snapshots__/theme.test.ts.snap
  src/__tests__/theme.test.ts
  src/components/common/CustomButton.tsx
  src/style/theme.ts
Labels: enhancement

#41 Refactor: SelectBox 리팩토링
  src/components/common/SelectBox.tsx
  src/constants/sportsConstants.ts
Labels: Refactor
