Repository Programmers-Coach-Coach/Coach-Coach-client, pull requests merged in 2024-09, with the labels that each got.

#304 Docs: 역할 분담
  README.md
Labels: documentation

#309 Docs: 개발 포인트의 트렁크 기반 전략 추가
  README.md
Labels: documentation

#310 Update README.md
  README.md
Labels: enhancement

#312 Docs: 트렁크 기반 전략에서 관련 이미지 추가
  README.md
Labels: documentation

#315 Refactor: 이미지 최적화
  package-lock.json
  package.json
  src/components/mypage/ProfileSection.tsx
Labels: Refactor

#318 Refactor: 유저 프로필 로그 삭제
  src/components/mypage/ProfileSection.tsx
Labels: Refactor

#319 Feat: 디바운스 적용
  src/components/coach/CoachList.tsx
  src/hooks/useDebounce.ts
Labels: enhancement

#321 Refactor: imgix (이미지 CDN)을 사용한 이미지 사이즈 최적화
  src/components/coach/Coach.tsx
  src/utils/imgix.ts
Labels: enhancement
