Repository Programmers-Coach-Coach/Coach-Coach-client, pull requests merged in 2024-08, with the labels that each got.

#47 Refactor/layout
  jest.config.cjs
  src/App.tsx
  src/assets/images/Logo.png
  src/components/common/Header/DetailHeader.tsx
  src/components/layout/Layout.tsx
  src/utils/a.ts
  src/utils/getTitle.ts
  src/utils/isAuthPage.ts
Labels: Refactor

#49 Feature/sign-up
  src/App.tsx
  src/components/common/AuthInput/AuthInput.tsx
  src/pages/Signup.tsx
Labels: enhancement

#51 Feat: main page UI 작성
  jest.config.cjs
  package-lock.json
  package.json
  src/components/common/Heart.tsx
  src/components/home/PopularCoaches.tsx
  src/components/home/SportsList.tsx
  src/components/home/common/HomeHeader.tsx
  src/data/coach.ts
  src/data/sportsList.ts
  src/models/home.model.ts
  src/pages/Home.tsx
  src/style/global.ts
  test-setup.js
Labels: Design

#52 Feature/login UI
  src/assets/images/kakao-login.png
  src/components/KakaoLogin.tsx
  src/components/common/AuthInput/AuthInput.tsx
  src/pages/Login.tsx
Labels: enhancement, Refactor, Design

#55 Chore: 새 백엔드 API 엔드포인트 'api/vi'에 맞게 BASE_URL 수정
  src/api/http.ts
  vite.config.ts
Labels: Chore

#57 Feature/icon component
  src/components/Icon/Icon.tsx
  src/components/common/Footer/Footer.tsx
  src/components/common/modal/contents/FooterPicker.tsx
  src/constants/assets.tsx
  src/data/modal.ts
Labels: Refactor

#59 Refactor/theme
  src/__tests__/__snapshots__/theme.test.ts.snap
  src/__tests__/theme.test.ts
  src/style/theme.ts
Labels: Refactor, Design

#63 Fix: 폰트를 적용하지 못하는 오류 해결
  index.html
  src/App.tsx
  src/style/global.ts
Labels: bug

#66 Refactor/login
  src/App.tsx
  src/pages/Login.tsx
Labels: Refactor, Design

#68 Refactor/theme change
  src/App.tsx
  src/__tests__/__snapshots__/theme.test.ts.snap
  src/__tests__/theme.test.ts
  src/assets/images/Logo.png
  src/assets/images/kakao-login.png
  src/assets/images/kakaoLogin.png
  src/components/common/Button/CustomButton.tsx
  src/components/common/Button/KakaoLogin.tsx
  src/components/common/Footer/Footer.tsx
  src/components/common/Header/DetailHeader.tsx
  src/components/common/InputField/CheckBox/Heart.tsx
  src/components/common/InputField/Select/SelectBox.tsx
  src/components/common/InputField/Text/AuthInput.tsx
  src/components/common/Title.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/contents/ActionModalInner.tsx
  src/components/common/modal/contents/FooterPicker.tsx
  src/components/common/modal/contents/RoutinePicker.tsx
  src/components/home/PopularCoaches.tsx
  src/components/home/common/HomeHeader.tsx
  src/pages/Detail.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
  src/style/global.ts
  src/style/theme.ts
Labels: Refactor

#71 Refactor/sign, Login 페이지 UI 수정
  src/__tests__/__snapshots__/theme.test.ts.snap
  src/__tests__/theme.test.ts
  src/components/common/InputField/Text/AuthInput.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
  src/style/theme.ts
Labels: Refactor, Design

#78 Remove: vite proxy 삭제
  vite.config.ts
Labels: Chore

#81 Feature/sentry
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/components/Error/ErrorBoundary.tsx
  src/components/layout/Layout.tsx
  src/main.tsx
  src/pages/Error.tsx
  vite.config.ts
Labels: enhancement

#84 Feature/icon modal
  src/components/common/Footer/Footer.tsx
  src/components/common/modal/Modal.tsx
  src/utils/animation.ts
Labels: enhancement

#86 Feat: 코치 리스트 및 faker.js 설치
  package-lock.json
  package.json
  src/App.tsx
  src/components/Error/ErrorBoundary.tsx
  src/components/coach/Coach.tsx
  src/components/coach/CoachDataList.tsx
  src/components/common/Button/CustomButton.tsx
  src/components/common/Button/KakaoLogin.tsx
  src/data/coach.ts
  src/main.tsx
  src/models/coach.model.ts
  src/models/sports.model.ts
  src/pages/CoachList.tsx
  src/style/theme.ts
  src/utils/faker.ts
  src/utils/getTitle.ts
  vite.config.ts
Labels: Chore

#92 Feature/coach list
  src/utils/faker.ts
Labels: Refactor

#90 Feature/mypage UI
  package-lock.json
  package.json
  src/App.tsx
  src/__tests__/__snapshots__/theme.test.ts.snap
  src/__tests__/theme.test.ts
  src/api/auth.api.ts
  src/components/common/Button/CustomButton.tsx
  src/components/common/InputField/Select/SelectBox.tsx
  src/components/mypage/CoachProfileSection.tsx
  src/components/mypage/ProfileSection.tsx
  src/components/tab/BasicTabs.tsx
  src/constants/apiPath.ts
  src/data/coachProfile.ts
  src/data/profile.ts
  src/hooks/queries/useFetchCoachProfile.ts
  src/hooks/queries/useFetchUserProfile.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/myCoachDetail.ts
  src/mocks/handlers/myDetail.ts
  src/models/auth.model.ts
  src/models/coach.model.ts
  src/pages/Mypage.tsx
  src/style/theme.ts
Labels: enhancement, Refactor

#98 Design: 코치 리스트 필터 UI
  src/components/coach/CaochListFilter.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/contents/FilterPicker.tsx
  src/constants/assets.tsx
  src/data/sportsList.ts
  src/hooks/useCoachFilter.ts
  src/hooks/useModal.ts
  src/models/coach.model.ts
  src/models/sports.model.ts
  src/pages/CoachList.tsx
Labels: Design

#100 Feature/signup logic
  src/App.tsx
  src/api/auth.api.ts
  src/components/common/InputField/Text/AuthInput.tsx
  src/components/signup/SignupForm.tsx
  src/constants/regex.ts
  src/hooks/useAuth.ts
  src/models/auth.model.ts
  src/pages/Signup.tsx
Labels: enhancement

#101 Feature/login logic
  src/api/auth.api.ts
  src/assets/images/kakaoLogin.png
  src/components/common/Button/KakaoLogin.tsx
  src/components/login/LoginForm.tsx
  src/constants/apiPath.ts
  src/hooks/useAuth.ts
  src/models/auth.model.ts
  src/pages/Login.tsx
  src/store/authStore.ts
Labels: enhancement

#88 Feature/routine
  package-lock.json
  package.json
  src/App.tsx
  src/__tests__/__snapshots__/theme.test.ts.snap
  src/__tests__/theme.test.ts
  src/api/http.ts
  src/api/routine.api.ts
  src/components/common/Card/Card.tsx
  src/components/common/InputField/Select/SelectBoxInModal.tsx
  src/components/common/InputField/Text/InputInModal.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/contents/ActionModalInner.tsx
  src/components/common/modal/contents/FooterPicker.tsx
  src/components/common/modal/contents/RoutineContents.tsx
  src/components/common/modal/contents/RoutinePicker.tsx
  src/components/routine/Routine.tsx
  src/constants/apiPath.ts
  src/constants/assets.tsx
  src/data/modal.ts
  src/data/routine.ts
  src/hooks/useRoutine.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/routine.ts
  src/models/routine.model.ts
  src/pages/MyRoutine.tsx
  src/store/modalInfo.store.ts
  src/style/theme.ts
  src/utils/getTitle.ts
Labels: enhancement

#105 Fix: useAuth 오타 수정 및 주석 삭제
  src/api/auth.api.ts
  src/api/coach.api.ts
  src/components/mypage/CoachProfileSection.tsx
  src/components/mypage/ProfileSection.tsx
  src/components/signup/SignupForm.tsx
  src/constants/apiPath.ts
  src/constants/assets.tsx
  src/hooks/useAuth.ts
Labels: Refactor

#107 Design/filter UI
  src/__tests__/__snapshots__/theme.test.ts.snap
  src/api/coach.api.ts
  src/components/Icon/Icon.tsx
  src/components/coach/CaochListFilter.tsx
  src/components/coach/CoachList.tsx
  src/components/common/modal/contents/FilterPicker.tsx
  src/components/sports/SportsList.css.ts
  src/components/sports/SportsList.tsx
  src/constants/assets.tsx
  src/data/sportsList.ts
  src/hooks/useCoachFilter.ts
  src/models/coach.model.ts
  src/pages/CoachList.tsx
  src/style/theme.ts
Labels: Design

#111 Chore: GA 적용
  jest.config.cjs
  package-lock.json
  package.json
  src/api/http.ts
  src/components/layout/Layout.tsx
  src/mocks/handlers/coach.ts
  src/mocks/handlers/home.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/profile.ts
  src/mocks/handlers/routine.ts
  vite.config.ts
Labels: enhancement, Chore

#113 Fix: 배포환경에서 다른 페이지로 이동했을 때 404에러가 뜨는 오류 해결
  public/_redirects
Labels: bug

#114 Feature/story book
  .eslintrc.cjs
  .gitignore
  .storybook/main.ts
  .storybook/preview-decorators.tsx
  .storybook/preview.ts
  package-lock.json
  package.json
  src/stories/AuthInput.stories.tsx
  src/stories/Card.stories.ts
  src/stories/Configure.mdx
  src/stories/CustomButton.stories.ts
  src/stories/Footer.stories.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
Labels: enhancement

#116 Feature/check password
  src/App.tsx
  src/api/auth.api.ts
  src/components/checkpassword/CheckPasswordForm.tsx
  src/constants/apiPath.ts
  src/hooks/useAuth.ts
  src/models/auth.model.ts
  src/pages/CheckPassword.tsx
  src/store/authStore.ts
  src/utils/getTitle.ts
Labels: enhancement

#118 Design: 검색창 ui 구현
  src/components/common/InputField/search/Search.tsx
  src/constants/assets.tsx
  src/pages/CoachList.tsx
  src/pages/Home.tsx
Labels: Design

#122 Refactor/mypage
  package-lock.json
  package.json
  src/__tests__/__snapshots__/theme.test.ts.snap
  src/__tests__/theme.test.ts
  src/api/auth.api.ts
  src/components/common/Card/ReviewCard.tsx/ReviewCard.tsx
  src/components/loading/Loading.tsx
  src/components/mypage/AddressSearchField.tsx
  src/components/mypage/CoachProfileSection.tsx
  src/components/mypage/ProfileSection.tsx
  src/constants/apiPath.ts
  src/data/coachProfile.ts
  src/hooks/useAuth.ts
  src/models/auth.model.ts
  src/models/coach.model.ts
  src/style/theme.ts
  src/utils/genderUtils.ts
Labels: enhancement, Refactor

#123 Feat: 알림 페이지 ui 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/notice-heart.png
  src/assets/images/notice-message.png
  src/assets/images/notice-speaker.png
  src/components/card/NotificationCard.tsx
  src/components/common/Footer/Footer.tsx
  src/data/notification.ts
  src/models/notification.model.ts
  src/pages/Notification.tsx
  src/utils/format.ts
  src/utils/getTitle.ts
Labels: Design

#127 Feature/routine infinite
  src/api/routine.api.ts
  src/components/common/Footer/Footer.tsx
  src/components/common/modal/contents/ActionModalInner.tsx
  src/components/common/modal/contents/RoutinePicker.tsx
  src/components/layout/Layout.tsx
  src/components/routine/RoutineList.tsx
  src/data/responseMessage.ts
  src/data/routine.ts
  src/hooks/useRoutine.ts
  src/mocks/handlers/routine.ts
  src/models/responseMessage.model.ts
  src/models/routine.model.ts
  src/pages/MyRoutine.tsx
Labels: enhancement

#130 Feature/my coach
  src/App.tsx
  src/api/coach.api.ts
  src/components/Profile/Profile.tsx
  src/components/Profile/ProfileList/MyCoachesProfileList.tsx
  src/components/common/Empty/Empty.tsx
  src/constants/apiPath.ts
  src/data/coach.ts
  src/data/modal.ts
  src/hooks/useCoachList.ts
  src/mocks/handlers/coach.ts
  src/models/coach.model.ts
  src/pages/MyCoach.tsx
  src/utils/getTitle.ts
Labels: enhancement

#125 Design: 신체 기록 UI
  src/App.tsx
  src/__tests__/__snapshots__/theme.test.ts.snap
  src/__tests__/theme.test.ts
  src/components/modal/PhysicalRecordInner.tsx
  src/components/record/physicalRecord/PhysicalRecord.tsx
  src/components/record/physicalRecord/PhysicalRecordInputs.tsx
  src/pages/RecordDatail.tsx
  src/style/theme.ts
  src/utils/getTitle.ts
Labels: Design

#134 Design: 카테고리 드롭다운 UI
  src/components/Icon/IconButton.tsx
  src/components/common/InputField/dropdown/CategoryDropdown.tsx
  src/constants/assets.tsx
  src/models/routine.model.ts
Labels: Design

#136 Feature/profile routine
  src/App.tsx
  src/api/routine.api.ts
  src/components/Profile/Profile.tsx
  src/components/Profile/ProfileList/MyCoachesProfileList.tsx
  src/components/layout/Layout.tsx
  src/components/routine/Routine.tsx
  src/components/routine/RoutineList.tsx
  src/hooks/useRoutine.ts
  src/models/routine.model.ts
  src/pages/Routine/CoachRoutine.tsx
  src/pages/Routine/MyRoutine.tsx
  src/store/profileInfo.store.ts
Labels: enhancement

#145 Fix: 메인 데이터 가져오기 API의 응답 인터페이스 수정
  src/api/coach.api.ts
  src/components/coach/Coach.tsx
  src/components/coach/PopularCoaches.tsx
  src/constants/apiPath.ts
  src/data/coach.ts
  src/hooks/useCoachList.ts
  src/mocks/handlers/coach.ts
  src/mocks/handlers/home.ts
  src/mocks/handlers/index.ts
  src/models/coach.model.ts
Labels: enhancement

#142 Design: 신체 기록 선차트 및 탭 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/chart/LineChart.tsx
  src/components/record/physicalRecord/PhysicalRecordChart.tsx
  src/components/tab/PhysicalTabs.tsx
  src/pages/Record.tsx
  src/utils/getTitle.ts
Labels: Design

#146 Feat/coach detail UI
  src/App.tsx
  src/api/auth.api.ts
  src/api/coach.api.ts
  src/components/coach/BasicInfo.tsx
  src/components/coach/Coach.tsx
  src/components/coach/DetailInfo.tsx
  src/components/common/Card/ReviewCard.tsx/ReviewCard.tsx
  src/components/modal/ReviewInner.tsx
  src/components/mypage/CoachProfileSection.tsx
  src/constants/assets.tsx
  src/data/coachProfile.ts
  src/hooks/queries/useCoachDetail.ts
  src/models/coach.model.ts
  src/pages/Coach.tsx
  src/style/theme.ts
  src/utils/getTitle.ts
  vite.config.ts
Labels: Design

#148 Feat: 알림 API 연결
  src/api/notification.api.ts
  src/components/common/Empty/Empty.tsx
  src/constants/apiPath.ts
  src/hooks/queries/useNotification.ts
  src/pages/Notification.tsx
Labels: enhancement

#150 Refactor/my profile
  src/App.tsx
  src/api/auth.api.ts
  src/assets/images/basicProfile.png
  src/components/checkpassword/CheckPasswordForm.tsx
  src/components/common/InputField/Text/AuthInput.tsx
  src/components/layout/PrivateLayout.tsx
  src/components/login/LoginForm.tsx
  src/components/mypage/CoachProfileSection.tsx
  src/components/mypage/ProfileSection.tsx
  src/constants/apiPath.ts
  src/data/profile.ts
  src/hooks/useAuth.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/profile.ts
  src/models/auth.model.ts
  src/pages/CheckPassword.tsx
Labels: enhancement, Refactor

#154 Feat: 알림 개별 삭제 API 연결
  src/App.tsx
  src/api/notification.api.ts
  src/components/card/NotificationCard.tsx
  src/constants/apiPath.ts
  src/data/notification.ts
  src/hooks/queries/useNotification.ts
  src/models/notification.model.ts
  src/pages/Notification.tsx
Labels: enhancement

#156 Refactor: 코치 디테일 리팩토링
  src/App.tsx
  src/components/coach/BasicInfo.tsx
  src/components/coach/DetailInfo.tsx
  src/components/common/Card/ReviewCard.tsx/RatingStars.tsx
  src/components/common/Card/ReviewCard.tsx/ReviewCard.tsx
  src/components/modal/ReviewInner.tsx
  src/hooks/queries/useCoachDetail.ts
  src/pages/Coach.tsx
  src/style/theme.ts
  src/utils/getTitle.ts
Labels: enhancement

#158 Feat: 토큰 재발급 api, 인터셉터 설정
  src/api/auth.api.ts
  src/api/http.ts
  src/constants/apiPath.ts
  src/pages/CheckPassword.tsx
  src/store/authStore.ts
  src/utils/logoutUtil.ts
Labels: enhancement

#161 Feat: 알림 전체 삭제 API 연결
  src/api/notification.api.ts
  src/hooks/queries/useNotification.ts
  src/pages/Notification.tsx
Labels: enhancement

#165 Feat/record detail UI
  src/App.tsx
  src/components/common/InputField/dropdown/CategoryDropdown.tsx
  src/components/record/exerciseRecord/ExerciseCalendar.tsx
  src/components/record/exerciseRecord/ExerciseDetail.tsx
  src/data/modal.ts
  src/pages/Record.tsx
  src/pages/RecordDatail.tsx
Labels: Design

#167 Feat: 문의하기 API 연결
  src/api/coach.api.ts
  src/hooks/queries/useContact.ts
  src/pages/Coach.tsx
  src/utils/error.ts
Labels: enhancement

#170 Refactor: 프로필 페이지 리팩토링
  src/api/auth.api.ts
  src/components/layout/PrivateLayout.tsx
  src/components/mypage/AddressSearchField.tsx
  src/components/mypage/CoachProfileSection.tsx
  src/components/mypage/ProfileSection.tsx
  src/constants/apiPath.ts
  src/hooks/useAuth.ts
  src/main.tsx
  src/models/coach.model.ts
Labels: enhancement, Refactor

#176 Fix: 버튼 클릭안되는 오류 수정
  src/components/card/NotificationCard.tsx
Labels: bug

#178 Feat: 관심 등록 및 관심 수정 API 연결
  src/api/likes.api.ts
  src/components/Icon/IconButton.tsx
  src/components/coach/BasicInfo.tsx
  src/components/coach/Coach.tsx
  src/components/coach/PopularCoaches.tsx
  src/components/common/InputField/CheckBox/Heart.tsx
  src/constants/assets.tsx
  src/data/coachProfile.ts
  src/hooks/queries/useLikes.ts
  src/models/coach.model.ts
Labels: enhancement

#181 Feat: 좋아요 등록, 해제에 invalidateQueries 추가
  src/hooks/queries/useLikes.ts
Labels: bug

#179 Feat: 리뷰 등록 API 연결 및 리뷰 카드 디자인 변경
  src/api/review.api.ts
  src/components/coach/DetailInfo.tsx
  src/components/common/Card/ReviewCard.tsx/ReviewCard.tsx
  src/components/modal/ReviewInner.tsx
  src/hooks/queries/useReview.ts
  src/models/review.model.ts
Labels: enhancement

#187 Feat: 코치 리스트 필터들을 쿼리 스트링으로 추가
  src/api/coach.api.ts
  src/components/coach/CaochListFilter.tsx
  src/components/coach/Coach.tsx
  src/components/coach/CoachList.tsx
  src/components/common/InputField/search/Search.tsx
  src/components/common/modal/contents/FilterPicker.tsx
  src/components/sports/SportsList.tsx
  src/data/sportsList.ts
  src/hooks/useCoachFilter.ts
  src/hooks/useCoachList.ts
  src/models/coach.model.ts
  src/models/sports.model.ts
  src/pages/CoachList.tsx
Labels: enhancement

#188 Feat: 기록 API 연결
  src/api/record.api.ts
  src/components/chart/LineChart.tsx
  src/components/modal/PhysicalRecordInner.tsx
  src/components/record/exerciseRecord/ExerciseCalendar.tsx
  src/components/record/exerciseRecord/ExerciseDetail.tsx
  src/components/record/physicalRecord/PhysicalRecord.tsx
  src/components/record/physicalRecord/PhysicalRecordInputs.tsx
  src/constants/apiPath.ts
  src/constants/regex.ts
  src/hooks/queries/useRecord.ts
  src/hooks/useQueryString.ts
  src/models/record.model.ts
  src/pages/Record.tsx
  src/pages/RecordDatail.tsx
  src/utils/format.ts
Labels: enhancement

#190 Feat: 신체 기록 차트 API 연결
  src/api/record.api.ts
  src/components/chart/LineChart.tsx
  src/constants/apiPath.ts
  src/hooks/queries/useRecord.ts
  src/models/record.model.ts
  src/pages/Record.tsx
  src/utils/chart.ts
Labels: enhancement

#193 Refactor: 뒤로가기 연결하는 방식을 변경
  src/components/common/Header/DetailHeader.tsx
  src/components/common/Header/LogoHeader.tsx
  src/components/common/InputField/CheckBox/Heart.tsx
  src/hooks/queries/useLikes.ts
  src/utils/getTitle.ts
Labels: enhancement

#195 Refactor: 기록 페이지 관련 UI 변경
  src/components/common/Empty/Empty.tsx
  src/components/common/InputField/dropdown/CategoryDropdown.tsx
  src/components/record/exerciseRecord/ExerciseCalendar.tsx
  src/components/record/exerciseRecord/ExerciseDetail.tsx
  src/components/routine/Action.tsx
  src/pages/RecordDatail.tsx
Labels: enhancement

#197 Feat: 검색창 연결
  src/components/Icon/IconButton.tsx
  src/components/coach/CaochListFilter.tsx
  src/components/coach/CoachList.tsx
  src/components/common/InputField/search/Search.tsx
  src/hooks/useQueryString.ts
Labels: enhancement

#199 Refactor/mypage refactor
  src/App.tsx
  src/components/common/Card/ReviewCard.tsx/CoachProfileReview.tsx
  src/components/common/modal/contents/FooterPicker.tsx
  src/components/mypage/CoachProfileSection.tsx
  src/data/modal.ts
  src/hooks/useAuth.ts
  src/pages/CheckPassword.tsx
  src/pages/Login.tsx
  src/pages/Mypage.tsx
  src/utils/formatDate.ts
  src/utils/getTitle.ts
Labels: enhancement, Refactor

#200 Fix: 차트 정렬 및 차트 높이가 계속 변경하는 문제 해결
  src/components/chart/LineChart.tsx
  src/components/coach/PopularCoaches.tsx
  src/utils/chart.ts
Labels: bug

#202 Bug: 각종 버그 수정
  src/assets/images/profile.png
  src/components/coach/BasicInfo.tsx
  src/components/coach/Coach.tsx
  src/components/coach/PopularCoaches.tsx
  src/components/common/InputField/CheckBox/Heart.tsx
  src/components/common/InputField/dropdown/CategoryDropdown.tsx
  src/components/sports/SportsList.css.ts
  src/components/sports/SportsList.tsx
  src/hooks/queries/useLikes.ts
  src/hooks/useCoachFilter.ts
  src/utils/getTitle.ts
Labels: bug

#205 Bug: 차트 관련 버그 수정
  package-lock.json
  package.json
  src/components/chart/LineChart.tsx
  src/components/modal/PhysicalRecordInner.tsx
  src/components/record/physicalRecord/PhysicalRecord.tsx
  src/components/record/physicalRecord/PhysicalRecordInputs.tsx
  src/hooks/queries/useRecord.ts
Labels: bug

#207 Refactor: 마이페이지 리팩토링
  src/api/http.ts
  src/components/mypage/CoachProfileSection.tsx
  src/hooks/queries/useFetchCoachProfile.ts
  src/hooks/useFetchAuth.ts
  src/models/auth.model.ts
  src/utils/genderUtils.ts
Labels: Refactor

#211 Feat: 카카오톡 링크 디테일 페이지에 표시
  src/components/coach/CaochListFilter.tsx
  src/components/record/exerciseRecord/ExerciseCalendar.tsx
  src/pages/Coach.tsx
  src/pages/Notification.tsx
  src/pages/Routine/MemberRoutine.tsx
  src/pages/Routine/MyRoutine.tsx
  src/pages/Routine/RoutineDetail.tsx
  src/style/theme.ts
Labels: enhancement

#214 Feat: 푸터 이미지 변경
  src/components/Icon/Icon.tsx
  src/components/common/Footer/Footer.tsx
  src/constants/assets.tsx
  src/hooks/queries/useLikes.ts
  src/pages/Signup.tsx
Labels: Design

#216 Feat: search가 빈값도 요청할 수 있도록 수정
  src/components/coach/DetailInfo.tsx
  src/components/common/Card/ReviewCard.tsx/ReviewCard.tsx
  src/components/common/InputField/search/Search.tsx
  src/components/modal/ReviewInner.tsx
Labels: enhancement

#218 Feat:알림 삭제하면 바로 알림 개수에 반영되도록 auth 호출
  src/components/chart/LineChart.tsx
  src/components/coach/CoachList.tsx
  src/components/common/Footer/Footer.tsx
  src/hooks/queries/useNotification.ts
  src/pages/Home.tsx
  src/pages/Notification.tsx
Labels: bug

#220 Remove: 로그 제거
  src/components/coach/BasicInfo.tsx
  src/components/mypage/CoachProfileSection.tsx
  src/hooks/queries/useContact.ts
  src/pages/Coach.tsx
  src/pages/Home.tsx
  src/pages/MyCoach.tsx
Labels: enhancement

#224 Refactor: 코치 프로필 리팩토링
  src/components/mypage/CoachProfileSection.tsx
Labels: Refactor

#225 Feat: 홈 UI 리팩토링
  src/components/coach/Coach.tsx
  src/components/coach/PopularCoaches.tsx
  src/components/sports/SportsList.css.ts
  src/components/sports/SportsList.tsx
Labels: Design

#228 Refactor: 로그인 페이지 및 로그인 전역상태 리팩토링
  src/components/layout/Layout.tsx
  src/components/mypage/CoachProfileSection.tsx
  src/hooks/useAuth.ts
  src/pages/Login.tsx
  src/store/authStore.ts
Labels: Refactor

#221 Refactor: 코치가 아닌 경우 매칭 회원리스트 페이지 변경
  src/hooks/useMember.ts
  src/pages/ManageMember.tsx
Labels: Refactor

#233 Fix: 알림 정렬
  src/components/chart/LineChart.tsx
  src/components/common/InputField/CheckBox/Heart.tsx
  src/hooks/queries/useLikes.ts
  src/hooks/queries/useNotification.ts
  src/hooks/queries/useRecord.ts
  src/utils/chart.ts
  src/utils/sort.ts
Labels: bug

#232 Refactor: 매칭 회원페이지 및 코치프로필 리팩토링
  src/components/mypage/CoachProfileSection.tsx
  src/pages/ManageMember.tsx
Labels: Refactor

#235 Feat: 매칭 알림 추가
  src/assets/images/notice-match.png
  src/components/card/NotificationCard.tsx
  src/components/coach/PopularCoaches.tsx
  src/models/notification.model.ts
Labels: Design

#239 Feature/delete user modal
  src/components/mypage/ProfileSection.tsx
  src/hooks/useAuth.ts
  src/pages/Login.tsx
Labels: enhancement, Refactor

#242 Feat: 코치프로필에서 카카오톡 링크 validation 추가
  src/components/mypage/CoachProfileSection.tsx
  src/constants/regex.ts
Labels: enhancement, Refactor

#240 Feat: 리뷰 변경, 삭제
  src/api/review.api.ts
  src/components/Icon/IconButton.tsx
  src/components/card/NotificationCard.tsx
  src/components/coach/Coach.tsx
  src/components/coach/DetailInfo.tsx
  src/components/coach/PopularCoaches.tsx
  src/components/common/Card/ReviewCard.tsx/ReviewCard.tsx
  src/components/common/InputField/CheckBox/Heart.tsx
  src/components/modal/ReviewControl.tsx
  src/components/modal/ReviewInner.tsx
  src/components/mypage/CoachProfileSection.tsx
  src/components/mypage/ProfileSection.tsx
  src/components/record/exerciseRecord/ExerciseDetail.tsx
  src/components/routine/Routine.tsx
  src/data/coachProfile.ts
  src/hooks/queries/useCoachDetail.ts
  src/hooks/queries/useContact.ts
  src/hooks/queries/useReview.ts
  src/hooks/useDropdownClick.ts
  src/models/coach.model.ts
  src/pages/Coach.tsx
Labels: bug, enhancement, Design

#245 Fix: 코치프로필 404에러 수정
  src/components/mypage/CoachProfileSection.tsx
Labels: bug

#246 Fix: 각종 디자인 수정
  src/App.tsx
  src/components/Profile/Profile.tsx
  src/components/coach/BasicInfo.tsx
  src/components/coach/CaochListFilter.tsx
  src/components/coach/CoachList.tsx
  src/components/coach/DetailInfo.tsx
  src/components/common/Footer/Footer.tsx
  src/components/common/Header/DetailHeader.tsx
  src/components/common/InputField/Text/InputInModal.tsx
  src/components/common/InputField/dropdown/CategoryDropdown.tsx
  src/components/common/modal/Modal.tsx
  src/components/mypage/ProfileSection.tsx
  src/components/record/exerciseRecord/ExerciseDetail.tsx
  src/pages/Coach.tsx
  src/style/global.ts
  src/style/theme.ts
Labels: bug

#249 Refactor: 전반적인 리팩토링
  src/components/layout/Layout.tsx
  src/components/mypage/ProfileSection.tsx
  src/components/signup/SignupForm.tsx
  src/pages/Login.tsx
  src/pages/Mypage.tsx
  src/style/theme.ts
Labels: Refactor

#251 Fix: 리뷰와 UI 디자인 수정
  src/components/coach/BasicInfo.tsx
  src/components/coach/Coach.tsx
  src/components/coach/DetailInfo.tsx
  src/components/common/modal/Modal.tsx
Labels: bug

#253 Fix: 리뷰 추가 버튼 조건 버그 수정
  src/components/coach/DetailInfo.tsx
  src/components/common/InputField/dropdown/CategoryDropdown.tsx
  src/models/record.model.ts
Labels: bug

#255 Refactor: 코치 리스트 밑에 잘리는 오류
  src/assets/images/notice-warning.png
  src/components/card/NotificationCard.tsx
  src/components/coach/CoachList.tsx
  src/components/modal/ReviewControl.tsx
  src/models/notification.model.ts
  src/pages/Coach.tsx
Labels: Design

#257 Refactor/total refactor
  src/components/coach/Coach.tsx
  src/components/coach/DetailInfo.tsx
  src/components/common/modal/Modal.tsx
  src/components/mypage/AddressSearchField.tsx
  src/components/mypage/CoachProfileSection.tsx
  src/components/mypage/ProfileSection.tsx
  src/style/theme.ts
Labels: Refactor

#262 Refactor: 모든 마진 바텀 추가
  src/components/coach/CoachList.tsx
  src/components/coach/DetailInfo.tsx
  src/components/common/Card/ReviewCard.tsx/ReviewCard.tsx
  src/pages/Coach.tsx
  src/pages/CoachList.tsx
  src/pages/ManageMember.tsx
  src/pages/MyCoach.tsx
  src/pages/Notification.tsx
  src/pages/Record.tsx
  src/pages/RecordDatail.tsx
  src/pages/Routine/CoachRoutine.tsx
  src/pages/Routine/MemberRoutine.tsx
  src/pages/Routine/MyRoutine.tsx
  src/pages/Routine/RoutineDetail.tsx
Labels: bug

#260 Refactor: 코치 프로필 취소버튼 삭제
  src/components/mypage/CoachProfileSection.tsx
  src/pages/Mypage.tsx
Labels: Refactor

#264 Refactor: 코치 디테일 자기소개 글 넘치는 것 수정
  src/components/coach/DetailInfo.tsx
Labels: Refactor

#268 Refactor: 전체적인 UI 패딩 조정
  src/pages/CheckPassword.tsx
  src/pages/ManageMember.tsx
  src/pages/Mypage.tsx
Labels: Refactor, Design

#271 Refactor: 코치 전용 프로필 이미지 크기 조정
  src/components/mypage/CoachProfileSection.tsx
Labels: Refactor, Design

#273 Refactor: lazyloading 외 다양한 디자인 수정
  package-lock.json
  package.json
  src/components/card/NotificationCard.tsx
  src/components/coach/PopularCoaches.tsx
  src/components/common/modal/contents/ActionModalInner.tsx
  src/components/sports/SportsList.css.ts
  src/components/sports/SportsList.tsx
  src/style/theme.ts
Labels: enhancement

#274 Refactor/lazy loading
  src/components/coach/PopularCoaches.tsx
  src/components/sports/SportsList.tsx
Labels: bug

#279 Fix: 인기있는 코치의 description을 자동으로 늘어나게 설정
  src/components/coach/PopularCoaches.tsx
Labels: Design

#287 Refactor:이미지 확장자 추가
  src/components/mypage/ProfileSection.tsx
  src/pages/Home.tsx
Labels: Refactor

#288 Add: 주소 추가
  index.html
  public/coach-coach.ico
  src/components/card/NotificationCard.tsx
  src/components/coach/BasicInfo.tsx
  src/components/coach/Coach.tsx
  src/components/coach/CoachList.tsx
  src/components/coach/PopularCoaches.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/contents/FooterPicker.tsx
  src/components/loading/Loading.tsx
  src/components/sports/SportsList.css.ts
  src/components/sports/SportsList.tsx
  src/pages/Routine/CoachRoutine.tsx
  src/pages/Routine/MemberRoutine.tsx
Labels: enhancement

#291 Refactor: 메인화면 padding 조절
  src/pages/Home.tsx
Labels: Refactor

#300 Refactor: http 및 코치프로필 모달 수정
  src/api/http.ts
  src/components/mypage/CoachProfileSection.tsx
Labels: Refactor, Design
